layout_spectrum: 0.7667921911925077
typography_spectrum: 0.3123374618589878
color:
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  brandStrength: 0.5596894479822367
  lightness: 0.06447888724505901
  saturation: 0.5189397097565234
  rhythmicContrast: 0.4366525155492127
name: theplayground
favicon: null
title: The Playground
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
