name: theplayground
favicon: null
layout_spectrum: 0.1378944267053157
typography_spectrum: 0.8014732054434717
title: The Playground
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#334760'
    - '#ffd600'
    - '#906f00'
    - '#d09e01'
    - '#fff57d'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
